In [2]:
import pandas as pd
 
columns = ['Timestamp','From Bank','Account','To Bank','Account.1',
           'Amount Received','Receiving Currency','Amount Paid',
           'Payment Currency','Payment Format','Is Laundering']
 
records = []
current_typology = None
current_pattern_id = 0
 
with open("../data/raw/HI-Small_Patterns.txt") as f:
    for line in f:
        line = line.strip()
        if line.startswith("BEGIN LAUNDERING ATTEMPT"):
            current_typology = line.split(" - ")[1].split(":")[0].strip()
            current_pattern_id += 1
        elif line.startswith("END LAUNDERING ATTEMPT"):
            current_typology = None
        elif line and current_typology:
            parts = line.split(",")
            if len(parts) == 11:
                row = dict(zip(columns, parts))
                row['Typology'] = current_typology
                row['Pattern_ID'] = current_pattern_id
                records.append(row)
 
patterns_df = pd.DataFrame(records)
print(patterns_df.shape)
patterns_df['Typology'].value_counts()

(3209, 13)

Typology
GATHER-SCATTER    716
SCATTER-GATHER    626
STACK             466
FAN-OUT           342
FAN-IN            318
CYCLE             287
BIPARTITE         263
RANDOM            191
Name: count, dtype: int64

### One example pattern (all its transactions) per typology

In [4]:
for typ in patterns_df['Typology'].unique():
    example_id = patterns_df[patterns_df['Typology'] == typ]['Pattern_ID'].iloc[0]
    print(f"\n=== {typ} — Pattern #{example_id} ===")
    display(patterns_df[patterns_df['Pattern_ID'] == example_id][
        ['Timestamp','Account','Account.1','Amount Paid','Payment Currency','Payment Format']
    ])

=== FAN-OUT — Pattern #1 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
0,2022/09/01 00:06,800737690,80011F990,2848.96,Euro,ACH
1,2022/09/01 04:33,800737690,80020C5B0,8630.40,Euro,ACH
2,2022/09/01 09:14,800737690,80006A5E0,35642.49,Yuan,ACH
3,2022/09/01 09:56,800737690,8007A5B70,5738987.96,US Dollar,ACH
4,2022/09/01 11:28,800737690,80093C0D0,7254.53,US Dollar,ACH
5,2022/09/01 13:13,800737690,80078E200,6990.87,US Dollar,ACH
6,2022/09/01 14:11,800737690,80066B990,12536.92,Euro,ACH
7,2022/09/02 15:40,800737690,8002CC310,3511.82,Euro,ACH
8,2022/09/02 21:23,800737690,8004030A0,16135.09,US Dollar,ACH
9,2022/09/02 23:10,800737690,800578800,12183.28,US Dollar,ACH
10,2022/09/03 09:29,800737690,800AAF0B0,15197.45,US Dollar,ACH
11,2022/09/03 14:22,800737690,8006FB970,4717.76,US Dollar,ACH
12,2022/09/04 07:35,800737690,800449990,19332.59,US Dollar,ACH
13,2022/09/04 09:10,800737690,800AEBA90,300.93,Euro,ACH
14,2022/09/04 12:03,800737690,800692550,2724.99,US Dollar,ACH
15,2022/09/04 15:48,800737690,8007486D0,15224.53,Euro,ACH

=== CYCLE — Pattern #2 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
16,2022/09/01 00:03,8013C4030,80BC62F10,58702.10,Yuan,ACH
17,2022/09/01 02:52,80BC62F10,80F025640,7332.87,Swiss Franc,ACH
18,2022/09/02 08:44,80F025640,80FD27570,26443.70,Shekel,ACH
19,2022/09/02 12:29,80FD27570,8090E8EB0,10621.24,Canadian Dollar,ACH
20,2022/09/03 10:20,8090E8EB0,804ABCE90,637140.60,Rupee,ACH
21,2022/09/03 12:08,804ABCE90,805494C30,621578.18,Rupee,ACH
22,2022/09/03 13:24,805494C30,801B949C0,7222.58,Euro,ACH
23,2022/09/04 03:24,801B949C0,803DE1580,892031.21,Yen,ACH
24,2022/09/04 09:44,803DE1580,80ACEE280,11364.12,Australian Dollar,ACH
25,2022/09/04 15:51,80ACEE280,8013C4030,7945.55,US Dollar,ACH

=== GATHER-SCATTER — Pattern #3 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
26,2022/09/01 00:04,811C597B0,811C599A0,34254.65,Saudi Riyal,ACH
27,2022/09/01 19:27,812D22980,811C599A0,5971.98,Saudi Riyal,ACH
28,2022/09/04 05:06,811B83280,811C599A0,50445.58,Saudi Riyal,ACH
29,2022/09/04 05:03,811C599A0,811C599A0,48649.42,Saudi Riyal,ACH
30,2022/09/04 14:59,811C599A0,811C597B0,64379.45,Saudi Riyal,ACH

=== STACK — Pattern #4 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
31,2022/09/02 12:36,8000DD890,80F52D550,14153.46,Swiss Franc,ACH
32,2022/09/03 19:52,80F52D550,80BEA98A0,11975.53,UK Pound,ACH
33,2022/09/01 10:19,8038D3520,801C0F2B0,13712.96,Euro,ACH
34,2022/09/03 05:06,801C0F2B0,80C1B9E20,333126.09,Mexican Peso,ACH
35,2022/09/01 09:22,80F6B88B0,8064545E0,11800.69,US Dollar,ACH
36,2022/09/03 08:27,8064545E0,80662A070,12331.00,US Dollar,ACH
37,2022/09/02 07:21,8014BDC90,80537F610,317448.19,Rupee,ACH
38,2022/09/04 19:11,80537F610,806C8F2A0,349281.29,Ruble,ACH
39,2022/09/01 15:05,80195DE20,801E2BC20,277.59,US Dollar,ACH
40,2022/09/04 09:31,801E2BC20,807E97240,230.27,UK Pound,ACH
41,2022/09/01 14:28,8009CF210,8011AB110,11964.97,US Dollar,ACH
42,2022/09/03 09:33,8011AB110,806C7CF80,11521.43,US Dollar,ACH
43,2022/09/02 19:34,803FF9220,81114D580,10295.53,US Dollar,ACH
44,2022/09/04 04:56,81114D580,809BD8BC0,9743.15,US Dollar,ACH
45,2022/09/02 07:37,80B3E96E0,801F8CCB0,17684.19,US Dollar,ACH
46,2022/09/03 04:39,801F8CCB0,801C92FF0,14819.83,Euro,ACH
47,2022/09/01 18:17,807A61380,802D53D80,16345.56,US Dollar,ACH
48,2022/09/04 01:29,802D53D80,80EE2B9B0,14199.39,Swiss Franc,ACH
49,2022/09/01 08:40,80B7347A0,802D878C0,6702.62,Euro,ACH
50,2022/09/03 01:44,802D878C0,8063F5290,7617.17,US Dollar,ACH
51,2022/09/01 16:51,80A1C7710,80A09CF50,3724.19,Euro,ACH
52,2022/09/02 12:47,80A09CF50,8067AD0A0,4646.02,US Dollar,ACH

=== RANDOM — Pattern #6 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
70,2022/09/01 01:57,81239C5C0,80C50EE70,4986.94,Mexican Peso,ACH
71,2022/09/01 08:59,80C50EE70,806EE41E0,19454.87,Ruble,ACH
72,2022/09/02 19:32,806EE41E0,8038A9100,1573.91,Yuan,ACH
73,2022/09/03 14:44,8038A9100,80B4D3030,219.12,US Dollar,ACH
74,2022/09/04 16:35,80B4D3030,8016E2C30,219.12,US Dollar,ACH

=== BIPARTITE — Pattern #10 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
99,2022/09/01 11:03,80103A420,802533E40,12347.20,US Dollar,ACH
100,2022/09/02 16:43,80211F620,8019C6830,15645.62,Euro,ACH
101,2022/09/02 12:00,800A75B90,80162B4B0,7687.95,US Dollar,ACH
102,2022/09/01 04:39,8010AA4F0,8015B5F50,9495.61,US Dollar,ACH
103,2022/09/02 08:17,800DD9900,8006F0580,488.77,US Dollar,ACH
104,2022/09/01 17:05,800587B60,802679190,5949.73,US Dollar,ACH
105,2022/09/01 16:19,801947FF0,800639010,13556.28,US Dollar,ACH
106,2022/09/02 08:58,800ACE160,800AEC6D0,12580.81,Euro,ACH
107,2022/09/01 11:32,8020543A0,8018DC000,4666.40,Euro,ACH
108,2022/09/01 07:39,801A58F80,80048D890,5019.15,Euro,ACH
109,2022/09/01 09:50,800BBBEC0,801732D60,9435.24,US Dollar,ACH
110,2022/09/01 19:00,8010647D0,801CFFF90,10205.61,US Dollar,ACH
111,2022/09/02 11:44,801BA48E0,80044F690,1581.32,Euro,ACH

=== FAN-IN — Pattern #13 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
124,2022/09/01 04:47,811B83280,811C597B0,13148.66,Saudi Riyal,ACH
125,2022/09/04 16:56,811C599A0,811C597B0,24189.19,Saudi Riyal,ACH

=== SCATTER-GATHER — Pattern #18 ===

,Timestamp,Account,Account.1,Amount Paid,Payment Currency,Payment Format
165,2022/09/01 07:57,808338D40,8095B6AF0,20649.41,Canadian Dollar,ACH
166,2022/09/03 05:33,8095B6AF0,80AEBECB0,13387.39,US Dollar,ACH
167,2022/09/02 08:55,808338D40,803892E30,93566.30,Yuan,ACH
168,2022/09/02 07:13,803892E30,80AEBECB0,13970.12,US Dollar,ACH
169,2022/09/02 13:04,808338D40,806D47B10,10245.65,US Dollar,ACH
170,2022/09/01 08:40,806D47B10,80AEBECB0,10104.07,US Dollar,ACH
171,2022/09/04 00:16,808338D40,801396710,17678.33,US Dollar,ACH
172,2022/09/03 14:26,801396710,80AEBECB0,14175.03,US Dollar,ACH
173,2022/09/04 13:53,808338D40,80B9F0EE0,7930.88,Euro,ACH
174,2022/09/01 09:31,80B9F0EE0,80AEBECB0,7678.43,US Dollar,ACH
175,2022/09/02 12:32,808338D40,80ABDD6E0,2962.96,Euro,ACH
176,2022/09/01 19:20,80ABDD6E0,80AEBECB0,2876.57,US Dollar,ACH
177,2022/09/04 10:24,808338D40,801DA8990,3072.27,US Dollar,ACH
178,2022/09/02 18:37,801DA8990,80AEBECB0,3055.18,US Dollar,ACH
179,2022/09/04 16:06,808338D40,806DA0590,702720.03,Ruble,ACH
180,2022/09/01 18:40,806DA0590,80AEBECB0,9031.93,US Dollar,ACH
181,2022/09/02 11:11,808338D40,80A32F2B0,9970.25,US Dollar,ACH
182,2022/09/04 05:33,80A32F2B0,80AEBECB0,9970.25,US Dollar,ACH
183,2022/09/02 13:30,808338D40,806694250,8514.12,US Dollar,ACH
184,2022/09/04 08:09,806694250,80AEBECB0,6932.43,US Dollar,ACH
185,2022/09/02 23:03,808338D40,81024EED0,49099.32,Shekel,ACH
186,2022/09/03 11:28,81024EED0,80AEBECB0,14539.33,US Dollar,ACH
187,2022/09/04 14:41,808338D40,803CA44E0,3927.81,US Dollar,ACH
188,2022/09/03 11:37,803CA44E0,80AEBECB0,4369.39,US Dollar,ACH
189,2022/09/02 19:08,808338D40,800AB4E80,19101.60,US Dollar,ACH
190,2022/09/04 21:37,800AB4E80,80AEBECB0,19101.60,US Dollar,ACH
191,2022/09/05 07:40,808338D40,80EF96640,51805.35,Yuan,ACH
192,2022/09/05 07:23,80EF96640,80AEBECB0,6349.41,US Dollar,ACH
193,2022/09/01 09:04,808338D40,804162D10,1449610.43,Yen,ACH
194,2022/09/02 16:57,804162D10,80AEBECB0,13753.42,US Dollar,ACH
195,2022/09/02 10:14,808338D40,80CB4E960,6004.01,UK Pound,ACH
196,2022/09/03 13:17,80CB4E960,80AEBECB0,7361.11,US Dollar,ACH